### ISSUE TITLE
Registry populate with packages

### ISSUE THREAD

**Issue by kmturley** [open-audio-stack/open-audio-stack-registry#1]
Once registry prototype has been reviewed, populate with more data so it is actually useful.

**Comment by dromer** [comment]
Be careful with copy-paste between yaml files because I'm already seeing bad information being used.

**Comment by kmturley** [comment]
Thanks, yes trying to populate plugin packagaes from my StudioRack project.
If you spot any issues feel free to link to the yaml file and I can correct, or you can submit a PR.

I plan to implement better yaml validation to validate fields and values in more detail.
That will likely find manual issues too.

**Comment by dromer** [comment]
For instance: https://github.com/open-audio-stack/open-audio-stack-registry/blob/main/src/plugins/distrho/dpf-plugins/1.7.0/index.yaml#L3

**Comment by kmturley** [comment]
Thanks fixed here: https://github.com/open-audio-stack/open-audio-stack-registry/commit/328fd8bbe0fd73f8703e617b4e2418d934356af3

**Comment by kmturley** [comment]
62 plugin packages added from StudioRack registry.
Feature-parity allows deprecation for StudiosRack registry.
