### ISSUE TITLE
if a plugin is being viewed, all projects which contain that plugin should be listed somewhere on that page

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#23]
Project - File which contains song data, in a format only for a specific DAW(s).

also this should be vice versa, if a project is being used all plugins in the registry should be listed whilst those that are not will just be their name and "not available".

**Comment by dromer** [comment]
This is out of scope of the registry. This should go into owlplug or studiorack feature requests.

**Comment by RustoMCSpit** [comment]
i just checked owlplugs readme and it shows this, im not sure if this is a breaking change but i'll move it to those repos. thank you dromer

DAW Projects analysis

OwlPlug can scan DAW projects to extract referenced plugins. Plugins references in project files are compared to plugins installed in configured directories. This way, users can quickly identify missing plugins required to open projects.

The list of compatible DAWs is available in the [documentation](https://github.com/DropSnorz/OwlPlug/wiki/Projects-and-DAW-Support)

**Comment by kmturley** [comment]
Agree out-of-scope of Registry.
It is likely out-of-scope of the Manager specification too, as the Manager is for downloading/installing packagaes.
This is more likely a useful UI feature which could be implemented in specific plugin managers if they choose.
Great idea though!

**Comment by RustoMCSpit** [comment]
should a list of recommended best ui practices be made lol
