### ISSUE TITLE
"bit64" is not a proper ISA declaration

### ISSUE THREAD

**Issue by dromer** [open-audio-stack/open-audio-stack-registry#25]
As discussed previously the term `bit64` is really bad form.
It is not a common term that anyone uses and it's not tied to any specific ISA.

It is better to stick to the more common terms `amd64` or `x86_84` and `arm64` or `aarch64`.

**Comment by kmturley** [comment]
I agreed it isn't a standard. I was trying to use a term which would be easy for metadata and tagging. But realize this could cause confusion.

I will look at addressing it in the specification first:
https://docs.google.com/document/d/14ljz4XNXr02xgdDHksPMl2vaM-Jn-YnJ_VzI1WsvSKQ/edit

and then any changes will need to be reflected in code. Will track updates in this issue.

**Comment by kmturley** [comment]
<html><head></head><body><p>Node.js uses the <code inline="">process.arch</code> and <code inline="">process.platform</code> properties to indicate the current architecture and platform, which are similar but slightly different from GCC or compiler values. Below is a mapping of Node.js values to their equivalent GCC target values.</p>
<hr>
<h3><strong>Node.js <code inline="">process.arch</code> Values</strong></h3>

Node.js Value | Equivalent GCC/Compiler Architecture
-- | --
x64 | x86-64
ia32 | i386, i486, i586, i686
arm | armv7-a, arm-linux-gnueabihf
arm64 | arm64, armv8-a, aarch64-linux-gnu
mips | mips, mipsel (32-bit MIPS)
mips64 | mips64, mips64el (64-bit MIPS)
ppc | powerpc, powerpc-linux-gnu
ppc64 | powerpc64, powerpc64-linux-gnu
s390 | s390
s390x | s390x
riscv64 | rv64gc (RISC-V 64-bit)


<hr>
<h3><strong>Mappings to GCC Targets</strong></h3>
<ol>
<li>
<p><strong>Node.js on x64 Linux:</strong></p>
<ul>
<li><strong>Node.js</strong>:
<ul>
<li><code inline="">process.arch = 'x64'</code>, <code inline="">process.platform = 'linux'</code></li>
</ul>
</li>
<li><strong>GCC Target</strong>:
<ul>
<li><code inline="">x86_64-pc-linux-gnu</code></li>
</ul>
</li>
</ul>
</li>
<li>
<p><strong>Node.js on ARM macOS (Apple Silicon):</strong></p>
<ul>
<li><strong>Node.js</strong>:
<ul>
<li><code inline="">process.arch = 'arm64'</code>, <code inline="">process.platform = 'darwin'</code></li>
</ul>
</li>
<li><strong>GCC Target</strong>:
<ul>
<li><code inline="">arm64-apple-darwin</code></li>
</ul>
</li>
</ul>
</li>
<li>
<p><strong>Node.js on 32-bit ARM Linux:</strong></p>
<ul>
<li><strong>Node.js</strong>:
<ul>
<li><code inline="">process.arch = 'arm'</code>, <code inline="">process.platform = 'linux'</code></li>
</ul>
</li>
<li><strong>GCC Target</strong>:
<ul>
<li><code inline="">arm-linux-gnueabihf</code></li>
</ul>
</li>
</ul>
</li>
<li>
<p><strong>Node.js on 64-bit Windows:</strong></p>
<ul>
<li><strong>Node.js</strong>:
<ul>
<li><code inline="">process.arch = 'x64'</code>, <code inline="">process.platform = 'win32'</code></li>
</ul>
</li>
<li><strong>GCC Target</strong>:
<ul>
<li><code inline="">x86_64-w64-mingw32</code></li>
</ul>
</li>
</ul>
</li>
</ol>

**Comment by kmturley** [comment]
As a result, updated values would be:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-891ae03a-7fff-079c-3d02-4f0f9c84ec7c"><div dir="ltr" style="margin-left:0pt;" align="center">
Name | Description | Value
-- | -- | --
Advanced RISC Machine - 32-bit | ARM processors are commonly used in battery-powered devices, such as smartphones and tablets. | arm32
Advanced RISC Machine - 64-bit | ARM processors are commonly used in battery-powered devices, such as smartphones and tablets. | arm64
x86 machine - 32-bit | X86 processors are commonly used in desktop computers and laptops. | x32
x86 machine - 64-bit | X86 processors are commonly used in desktop computers and laptops. | x64

</div></b>

**Comment by kmturley** [comment]
Relevant documentation: https://llvm.org/doxygen/classllvm_1_1Triple.html

**Comment by dromer** [comment]
what about different bsd's

`lin/win/mac/bsd`?

**Comment by RustoMCSpit** [comment]
i mean, is bsd really worth the time to maintain it given its market share and general lack of support around audio software. i thought the same thing when this was first being drafted but i just didnt think it could be justified
