### ISSUE TITLE
multiple arguments for author tag

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#30]

**Comment by kmturley** [comment]
`author` attribute is related to the package, even if the package contains multiple files from different contributors. If it allowed for multiple values there would be more ambiguity who each person is, and would be more difficult to display and comprehend.

Having a single field forces the package owner to decide on a single value. The field can be a person's name or an org/company name for multiple people. Other package managers do the same for these reasons.

Therefore closing as won't do.
