### ISSUE TITLE
warning if something is monophonic, old architecture, etc.

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#46]
this is really a studiorack issue but it's good to have documentation here for other website devs to add

**Comment by kmturley** [comment]
How do you mean? Out-of-date plugins?

**Comment by RustoMCSpit** [comment]
i see no point in removing them unless theyve malware

**Comment by kmturley** [comment]
I think we focus on adding x64 architceture. If the plugin happens to have x32 we can keep it in.
However for plugin managers, most might not even support x32, so those files would be ignored anyway
