### ISSUE TITLE
torrenting

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#58]
thinking about long term storage problems, i can imagine this would be a problem

**Comment by kmturley** [comment]
Not using torrents, it's a completely different technology and wouldn't be suited for this.

We are using GitHub Pages for hosting the registry and GitHub Releases for any downloads. They don't have any bandwidth limitations at the scale we are using them!

**Comment by RustoMCSpit** [comment]
just to be clear, do you plan on using github releases for projects? i mean it makes some sense for hosting but kills the possibility of future p2p sending via open audio or even real time collaboration (feature creep but im thinking years into the future with the daw integration)

**Comment by RustoMCSpit** [comment]
can this project use any url source as long as it supports git?

**Comment by kmturley** [comment]
Registries can link to any https URL on the web.

In theory registries could support torrent urls, but would require the manager to also support it.

Someone could do this in their own registry, but not planning to here.
