### ISSUE TITLE
Linux metadata not able to store this type of release

### ISSUE THREAD

**Issue by RustoMCSpit** [open-audio-stack/open-audio-stack-registry#63]
https://github.com/dsp56300/gearmulator/issues/226

The Linux Metadata does not account for different types of Linux system or distribution methods to my knowledge. If an uploader uses multiple methods, how do I store that?

**Comment by kmturley** [comment]
Registry specification current supports these Linux package formats:
- **AppImage** - Supported by practically all Linux distributions.
- **Debian Package (DEB)** - Debian, Ubuntu, Linux Mint, Pop!_OS, Zorin OS, Elementary OS, KDE Neon.
- **Red Hat Package (RPM)**- Red Hat Enterprise Linux (RHEL), Fedora, CentOS, AlmaLinux, Rocky Linux, openSUSE, Mageia.
- **Tarball** - Supported by practically all Linux distributions

Technically the specification allows for multiple Linux files e.g:
https://github.com/open-audio-stack/open-audio-stack-registry/blob/main/src/plugins/distrho/dpf-plugins/1.7.0/index.yaml#L20

Packages could have all four formats. The Manager would need need to only install the formats support by the system it's running. If we added Linux distributions as Operating Systems, then that would cause more work for plugin authors.

My preference would be not to supported Debian or Red Hat packages, as there are two other solutions which have better compatibility.

**Comment by kmturley** [comment]
Added a warning to avoid using deb and rpm file formats due to compatibility concerns:
https://github.com/open-audio-stack/open-audio-stack-core/commit/a1d54a228adc30694c0926db169764777133ea96
