### ISSUE TITLE
Specify hashing algorithm used for files referenced in the feed

### ISSUE THREAD

**Issue by DropSnorz** [open-audio-stack/open-audio-stack-registry#7]
The hash algorithm used to compute file digest must be clear and visible directly from data fields. Without the specification in hand, consumers can’t easily determine which algorithm should be used to verify digest.

I can see multiple solutions:

- Rename the field `hash` to `sha256hash` or similar. The [winget-pkgs solution](https://github.com/microsoft/winget-pkgs/blob/master/manifests/o/OwlPlug/OwlPlug/1.27.1/OwlPlug.OwlPlug.installer.yaml#L12)

- Add an extra object to hold one (or potentially multiple) digests using the algorithm as key. Kind of [Virus Total file attributes](https://docs.virustotal.com/reference/files) way of working. 

```json
"digests": {
  "sha256" : "281a82304a67dfdfe811493dd550842265749705e0b84a9cf16c4cae4730fea9",
  "md5" : "7f75ede34bc992a83e2e411b8d6594f1"
}
```

- Add algorithm as a prefix inside the hash value like `sha256:281a82304a67dfdfe811493dd550842265749705e0b84a9cf16c4cae4730fea9` The docker registry and [npm registry](https://blog.npmjs.org/post/172999548390/new-pgp-machinery) long-term solution for integrity checks.

We might introduce package signature support later, but I think we should make our integrity computing and validation as clear as possible now.

**Comment by kmturley** [comment]
The algorithm is shown in source code and specification, but we can rename the schema to clarify.
Are there any reasons to support multiple hashing algorithms?

If we don't need to support multiple types I favour renaming `hash` to `sha256`.
